jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.6.3'

      - task: gitversion/execute@0
        displayName: GitVersion
        inputs:
          useConfigFile: true
          configFilePath: gitversion.yml

      - task: DotNetCoreCLI@2
        displayName: Build Uno.WinUI3Convert
        inputs:
          command: build
          arguments: --verbosity detailed --configuration Release "-p:PackageOutputPath=$(Build.ArtifactStagingDirectory)" "-p:PackageVersion=$(GITVERSION.SemVer)"
          workingDirectory: src/Uno.WinUI3Convert

      - task: DotNetCoreCLI@2
        displayName: Install Uno.WinUI3Convert
        inputs:
          command: custom
          custom: tool
          arguments: install --global --add-source $(Build.ArtifactStagingDirectory) --version $(GITVERSION.SemVer) uno.winui3convert

      - powershell: winui3convert Tests\Microsoft.Toolkit.Uwp.UI.Controls.DataGrid Tests\out\Microsoft.Toolkit.Uwp.UI.Controls.DataGrid
        displayName: Convert Microsoft.Toolkit.Uwp.UI.Controls.DataGrid sources

      - task: MSBuild@1
        displayName: Build Microsoft.Toolkit.Uwp.UI.Controls.DataGrid
        inputs:
          solution: Tests/out/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid.csproj
          configuration: Release
          msbuildArguments: /ds /r
          maximumCpuCount: true

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          artifactName: Tool
